name: Python release on pypi

on:
  release:
    types:
      - released

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        poetry-version: [ 1.1.13 ]
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: poetry publish on pypi
        run: poetry publish --build --username=__token__ --password=${{secrets.PYPI_PASSWORD}}
